"""empty message

Revision ID: 4d6e7f85c2b5
Revises: 3b10df15926e
Create Date: 2024-10-26 01:09:43.912891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6e7f85c2b5'
down_revision = '3b10df15926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilidades', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.drop_column('habilidades')

    # ### end Alembic commands ###
