"""empty message

Revision ID: 6021cda95cab
Revises: 7fadc899ffe8
Create Date: 2024-10-28 17:07:32.297309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6021cda95cab'
down_revision = '7fadc899ffe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('galeria', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('horarios', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.drop_column('horarios')
        batch_op.drop_column('galeria')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
