"""empty message

Revision ID: 711c17d63cb9
Revises: 3b10df15926e
Create Date: 2024-10-25 17:03:08.136938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711c17d63cb9'
down_revision = '3b10df15926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paseos', schema=None) as batch_op:
        batch_op.alter_column('walker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('domicilio',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('horario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('tipo_de_paseo',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilidades', sa.Text(), nullable=True))
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('habilidades')

    with op.batch_alter_table('paseos', schema=None) as batch_op:
        batch_op.alter_column('tipo_de_paseo',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('horario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('domicilio',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('walker_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
