"""empty message

Revision ID: 72e898e3d8d9
Revises: 6021cda95cab
Create Date: 2024-10-28 17:23:19.619741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e898e3d8d9'
down_revision = '6021cda95cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.JSON(), nullable=True))
        batch_op.drop_column('horarios')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horarios', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
