"""empty message

Revision ID: 7fadc899ffe8
Revises: 28dee870aacc
Create Date: 2024-10-28 02:59:30.783738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fadc899ffe8'
down_revision = '28dee870aacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('fotoPerfil')

    # ### end Alembic commands ###
